name: Build and Package

on:
  push:
    branches:
      - ilogic
  pull_request:
    branches:
      - ilogic

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Navigate to project directory
      run: cd bworks.core

    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean package
      working-directory: bworks.core

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v2
      with:
        name: bworks.core-jar
        path: bworks.core/target/*.jar
